import { useEffect, useMemo, useState, type FormEvent } from 'react'
import CsvImport from './CsvImport'
import type { Transaction } from '../../types/transaction'

type Props = { transactions: Transaction[]; loading: boolean; onAddTransaction: (item: Omit<Transaction, 'id'>) => Promise<void>; onUpdateTransaction: (id: string, item: Omit<Transaction, 'id'>) => Promise<void>; onDeleteTransaction: (id: string) => Promise<void>; onImported: () => Promise<void> }
const money = (amount: number) => `₹${amount.toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
const blank = { title: '', amount: '', type: 'expense' as Transaction['type'], category: '', date: new Date().toISOString().slice(0, 10) }

function Transactions({ transactions, loading, onAddTransaction, onUpdateTransaction, onDeleteTransaction, onImported }: Props) {
  const [query, setQuery] = useState(''); const [type, setType] = useState<'all' | Transaction['type']>('all'); const [category, setCategory] = useState('all'); const [editor, setEditor] = useState<Transaction | null | 'new'>(null); const [form, setForm] = useState(blank); const [formError, setFormError] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { if (editor && editor !== 'new') setForm({ title: editor.title, amount: String(editor.amount), type: editor.type, category: editor.category, date: editor.date }); if (editor === 'new') setForm(blank); setFormError('') }, [editor])
  const categories = useMemo(() => [...new Set(transactions.map((item) => item.category))].sort(), [transactions])
  const filtered = useMemo(() => transactions.filter((item) => `${item.title} ${item.category}`.toLowerCase().includes(query.toLowerCase().trim()) && (type === 'all' || item.type === type) && (category === 'all' || item.category === category)), [transactions, query, type, category])
  const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + Number(item.amount), 0); const expenses = transactions.filter((item) => item.type === 'expense').reduce((sum, item) => sum + Number(item.amount), 0)
  async function submit(event: FormEvent) { event.preventDefault(); const amount = Number(form.amount); if (!form.title.trim() || !form.category.trim() || !form.date || !Number.isFinite(amount) || amount <= 0) { setFormError('Add a description, category, valid amount, and date.'); return }; setSaving(true); try { const item = { title: form.title.trim(), category: form.category.trim(), amount, type: form.type, date: form.date }; if (editor && editor !== 'new') await onUpdateTransaction(editor.id, item); else await onAddTransaction(item); setEditor(null) } catch { setFormError('Could not save this transaction. Please try again.') } finally { setSaving(false) } }
  return <section className="transactions-page">
    <header className="transactions-header"><div><p className="eyebrow">FINANCIAL ACTIVITY</p><h1>Transactions</h1><p className="page-description">Every rupee, clearly accounted for.</p></div><button className="primary-button" onClick={() => setEditor('new')}>+ Add transaction</button></header>
    <div className="summary-grid transaction-summary"><article className="summary-card balance-card"><span>Total balance</span><strong>{money(income - expenses)}</strong><p>Income minus expenses</p></article><article className="summary-card"><span>Total income</span><strong className="income-value">{money(income)}</strong><p>Money received</p></article><article className="summary-card"><span>Total expenses</span><strong className="expense-value">{money(expenses)}</strong><p>Money spent</p></article><article className="summary-card"><span>Entries</span><strong>{transactions.length}</strong><p>Transactions recorded</p></article></div>
    <section className="import-section"><div className="section-heading"><div><p className="eyebrow">QUICK IMPORT</p><h2>Bring in a CSV</h2><p>Columns: date, title, category, type, amount.</p></div></div><CsvImport onImported={onImported} /></section>
    {editor && <section className="editor-section"><div className="section-heading"><div><p className="eyebrow">{editor === 'new' ? 'NEW TRANSACTION' : 'UPDATE TRANSACTION'}</p><h2>{editor === 'new' ? 'Add transaction' : 'Edit transaction'}</h2></div><button className="icon-button" onClick={() => setEditor(null)} aria-label="Close form">×</button></div><form className="transaction-form" onSubmit={submit}><label className="form-field">Description<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="e.g. Groceries" autoFocus /></label><label className="form-field">Amount<input value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} type="number" min="0.01" step="0.01" placeholder="0.00" /></label><label className="form-field">Type<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as Transaction['type'] })}><option value="expense">Expense</option><option value="income">Income</option></select></label><label className="form-field">Category<input value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} placeholder="e.g. Food & dining" /></label><label className="form-field">Date<input value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} type="date" /></label>{formError && <p className="form-error">{formError}</p>}<div className="form-actions"><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : editor === 'new' ? 'Add transaction' : 'Save changes'}</button><button type="button" className="secondary-button" onClick={() => setEditor(null)}>Cancel</button></div></form></section>}
    <section className="transactions-section"><div className="section-heading"><div><p className="eyebrow">ACTIVITY</p><h2>All transactions</h2><p>{filtered.length} of {transactions.length} entries shown</p></div></div><div className="transaction-controls"><input aria-label="Search transactions" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search description or category" /><select aria-label="Filter by type" value={type} onChange={(e) => setType(e.target.value as typeof type)}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expense</option></select><select aria-label="Filter by category" value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All categories</option>{categories.map((name) => <option key={name}>{name}</option>)}</select>{(query || type !== 'all' || category !== 'all') && <button className="text-button" onClick={() => { setQuery(''); setType('all'); setCategory('all') }}>Clear filters</button>}</div>
      {loading ? <div className="empty-state"><h3>Loading transactions…</h3></div> : filtered.length === 0 ? <div className="empty-state"><div className="empty-icon">₹</div><h3>{transactions.length ? 'No matching transactions' : 'No transactions yet'}</h3><p>{transactions.length ? 'Try a different search or filter.' : 'Add an entry or import a CSV to get started.'}</p>{!transactions.length && <button className="primary-button" onClick={() => setEditor('new')}>+ Add transaction</button>}</div> : <div className="transactions-table-wrapper"><table className="transactions-table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Type</th><th>Amount</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td data-label="Date">{new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${item.date}T00:00:00`))}</td><td data-label="Description"><div className="transaction-description"><span className="transaction-avatar">{item.title.charAt(0).toUpperCase()}</span><strong>{item.title}</strong></div></td><td data-label="Category"><span className="category-pill">{item.category}</span></td><td data-label="Type"><span className={`type-pill type-${item.type}`}>{item.type}</span></td><td data-label="Amount"><strong className={item.type === 'income' ? 'amount-income' : 'amount-expense'}>{item.type === 'income' ? '+' : '−'}{money(Number(item.amount))}</strong></td><td><div className="transaction-actions"><button className="edit-button" onClick={() => setEditor(item)}>Edit</button><button className="delete-button" onClick={() => { if (window.confirm(`Delete ${item.title}?`)) void onDeleteTransaction(item.id) }}>Delete</button></div></td></tr>)}</tbody></table></div>}</section>
  </section>
}
export default Transactions
