import crypto from 'node:crypto'
import { Router } from 'express'
import { pool } from '../db.js'
import { createToken, hashPassword, passwordMatches, requireAuth } from '../utils/auth.js'

const router = Router()
router.post('/signup', async (req, res) => { const { name, email, password } = req.body; if (typeof name !== 'string' || !name.trim() || typeof email !== 'string' || !/^\S+@\S+\.\S+$/.test(email) || typeof password !== 'string' || password.length < 8) { res.status(400).json({ message: 'Enter a name, valid email, and password of at least 8 characters.' }); return } try { const user = await pool.query('INSERT INTO users (id, name, email, password_hash) VALUES ($1,$2,$3,$4) RETURNING id, name, email', [crypto.randomUUID(), name.trim(), email.trim().toLowerCase(), await hashPassword(password)]); const account = user.rows[0]; res.status(201).json({ user: account, token: createToken(account.id) }) } catch (error: unknown) { const code = error && typeof error === 'object' && 'code' in error ? error.code : ''; res.status(code === '23505' ? 409 : 500).json({ message: code === '23505' ? 'An account with this email already exists.' : 'Could not create account.' }) } })
router.post('/login', async (req, res) => { const { email, password } = req.body; if (typeof email !== 'string' || typeof password !== 'string') { res.status(400).json({ message: 'Email and password are required.' }); return } try { const result = await pool.query('SELECT id, name, email, password_hash FROM users WHERE email = $1', [email.trim().toLowerCase()]); const user = result.rows[0]; if (!user || !(await passwordMatches(password, user.password_hash))) { res.status(401).json({ message: 'Email or password is incorrect.' }); return } res.json({ user: { id: user.id, name: user.name, email: user.email }, token: createToken(user.id) }) } catch { res.status(500).json({ message: 'Could not sign in.' }) } })
router.get('/me', requireAuth, async (_req, res) => { const result = await pool.query('SELECT id, name, email FROM users WHERE id = $1', [res.locals.userId]); if (!result.rows[0]) { res.status(401).json({ message: 'Account not found.' }); return } res.json(result.rows[0]) })
export default router
