import logo from '../../assets/financetrack-logo.svg'
import { useState, type FormEvent } from 'react'
import { signIn, signUp, type User } from '../../services/authService'

type Props = { onContinue: (user: User, token: string) => void; onBack: () => void }

export default function Login({ onContinue, onBack }: Props) {
  const [mode, setMode] = useState<'signin' | 'signup'>('signin'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); setError(''); try { const result = mode === 'signin' ? await signIn(String(data.get('email')), String(data.get('password'))) : await signUp(String(data.get('name')), String(data.get('email')), String(data.get('password'))); localStorage.setItem('financetrack_token', result.token); onContinue(result.user, result.token) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not continue.') } finally { setBusy(false) } }
  return <main className="login-page"><section className="login-art" aria-hidden="true"><div className="login-orbit login-orbit-large" /><div className="login-orbit login-orbit-small" /><div className="login-label">YOUR MONEY<br />IN MOTION</div><div className="login-coin coin-one">₹</div><div className="login-coin coin-two">₹</div></section><section className="login-panel"><button className="back-link" onClick={onBack}>← Back to home</button><img src={logo} className="login-logo" alt="FinanceTrack" /><div className="login-copy"><p className="eyebrow">{mode === 'signin' ? 'WELCOME BACK' : 'START HERE'}</p><h1>{mode === 'signin' ? 'Sign in to see the full picture.' : 'Build a clearer money routine.'}</h1><p>Your financial activity stays organised in one private place.</p></div><form className="login-form" onSubmit={submit}>{mode === 'signup' && <label>Name<input name="name" placeholder="Your name" required /></label>}<label>Email address<input name="email" type="email" placeholder="you@example.com" required /></label><label>Password<input name="password" type="password" placeholder="At least 8 characters" required minLength={8} /></label>{error && <p className="form-error">{error}</p>}<button className="login-submit" disabled={busy}>{busy ? 'Please wait…' : mode === 'signin' ? 'Sign in' : 'Create account'}</button></form><p className="login-foot">{mode === 'signin' ? 'New to FinanceTrack?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'signin' ? 'signup' : 'signin')}>{mode === 'signin' ? 'Create an account' : 'Sign in'}</button></p></section></main>
}
